### ISSUE TITLE
Illegal instruction (core dumped)

### ISSUE THREAD

**Issue by mmolari** [bacpop/ggCaller#44]
Just wanted to report an error I ran into on the conda installation. Apologies if this is a duplicate!

I installed ggcaller in a new conda environment with 
```
conda create -n ggcaller -c conda-forge -c bioconda -c defaults ggcaller
```

this resulted in the following environment (with ggcaller v1.3.7 installed)

<details>
<summary>env.yaml</summary>
<br>

```yaml
name: ggcaller
channels:
  - bioconda
  - conda-forge
  - defaults
dependencies:
  - _libgcc_mutex=0.1
  - _openmp_mutex=4.5
  - argcomplete=3.5.2
  - argh=0.31.3
  - bcbio-gff=0.7.1
  - bifrost=1.3.5
  - biopython=1.80
  - boost-cpp=1.85.0
  - brotli=1.1.0
  - brotli-bin=1.1.0
  - bx-python=0.11.0
  - bzip2=1.0.8
  - ca-certificates=2024.12.14
  - cd-hit=4.8.1
  - certifi=2024.12.14
  - cffi=1.17.1
  - colorama=0.4.6
  - contourpy=1.3.0
  - cycler=0.12.1
  - diamond=2.1.11
  - fonttools=4.55.6
  - freetype=2.12.1
  - future=1.0.0
  - gawk=5.3.1
  - gettext=0.22.5
  - gettext-tools=0.22.5
  - gffutils=0.13
  - ggcaller=1.3.7
  - gmp=6.3.0
  - hmmer=3.4
  - icu=75.1
  - importlib-metadata=8.6.1
  - importlib-resources=6.5.2
  - importlib_resources=6.5.2
  - intbitset=3.0.2
  - joblib=1.4.2
  - kiwisolver=1.4.7
  - lcms2=2.16
  - ld_impl_linux-64=2.43
  - lerc=4.0.0
  - libasprintf=0.22.5
  - libasprintf-devel=0.22.5
  - libblas=3.9.0
  - libboost=1.85.0
  - libboost-devel=1.85.0
  - libboost-headers=1.85.0
  - libbrotlicommon=1.1.0
  - libbrotlidec=1.1.0
  - libbrotlienc=1.1.0
  - libcblas=3.9.0
  - libdeflate=1.23
  - libffi=3.4.2
  - libgcc=14.2.0
  - libgcc-ng=14.2.0
  - libgettextpo=0.22.5
  - libgettextpo-devel=0.22.5
  - libgfortran=14.2.0
  - libgfortran-ng=14.2.0
  - libgfortran5=14.2.0
  - libhwloc=2.11.2
  - libiconv=1.17
  - libjpeg-turbo=3.0.0
  - liblapack=3.9.0
  - liblzma=5.6.3
  - liblzma-devel=5.6.3
  - libnsl=2.0.1
  - libpng=1.6.46
  - libprotobuf=3.19.6
  - libsqlite=3.48.0
  - libstdcxx=14.2.0
  - libstdcxx-ng=14.2.0
  - libtiff=4.7.0
  - libuuid=2.38.1
  - libwebp-base=1.5.0
  - libxcb=1.17.0
  - libxcrypt=4.4.36
  - libxml2=2.13.5
  - libzlib=1.3.1
  - llvm-openmp=19.1.7
  - mafft=7.526
  - matplotlib-base=3.9.4
  - mkl=2022.2.1
  - mpfr=4.2.1
  - munkres=1.1.4
  - ncurses=6.5
  - networkx=3.2.1
  - ninja=1.12.1
  - numpy=1.26.4
  - openjpeg=2.5.3
  - openssl=3.4.0
  - packaging=24.2
  - pandas=2.2.3
  - patsy=1.0.1
  - pillow=11.1.0
  - pip=25.0
  - pthread-stubs=0.4
  - pycparser=2.22
  - pyfaidx=0.8.1.3
  - pyparsing=3.2.1
  - python=3.9.21
  - python-dateutil=2.9.0.post0
  - python-edlib=1.3.9.post1
  - python-tzdata=2025.1
  - python-wget=3.2
  - python_abi=3.9
  - pytorch=1.10.2
  - pytorch-cpu=1.10.2
  - pytz=2024.1
  - pyvcf3=1.0.3
  - qhull=2020.2
  - rapidnj=2.3.2
  - readline=8.2
  - scipy=1.13.1
  - seaborn=0.13.2
  - seaborn-base=0.13.2
  - setuptools=59.5.0
  - simplejson=3.19.3
  - six=1.17.0
  - sleef=3.7
  - snp-sites=2.5.1
  - statsmodels=0.14.4
  - tbb=2021.13.0
  - tk=8.6.13
  - tqdm=4.67.1
  - typing_extensions=4.12.2
  - tzdata=2025a
  - uncertainties=3.2.2
  - unicodedata2=16.0.0
  - wheel=0.45.1
  - xorg-libice=1.1.2
  - xorg-libsm=1.2.5
  - xorg-libx11=1.8.10
  - xorg-libxau=1.0.12
  - xorg-libxaw=1.0.16
  - xorg-libxcomposite=0.4.6
  - xorg-libxcursor=1.2.3
  - xorg-libxdamage=1.1.6
  - xorg-libxdmcp=1.1.5
  - xorg-libxext=1.3.6
  - xorg-libxfixes=6.0.1
  - xorg-libxi=1.8.2
  - xorg-libxinerama=1.1.5
  - xorg-libxmu=1.2.1
  - xorg-libxpm=3.5.17
  - xorg-libxrandr=1.5.4
  - xorg-libxrender=0.9.12
  - xorg-libxt=1.3.1
  - xz=5.6.3
  - xz-gpl-tools=5.6.3
  - xz-tools=5.6.3
  - zipp=3.21.0
  - zlib=1.3.1
  - zstd=1.5.6
prefix: /home/marco/miniconda3/envs/ggcaller
```

</details>

However when I run ggcaller (any command) I get the following error:

```
ggcaller --help
Illegal instruction (core dumped)
```

This is on Linux (Ubuntu 24.04). I hope I didn't do anything obviously wrong (apologies in this case!)

Thanks for all the support, and keep up the amazing work!

Marco
